/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { LogLoopStepJsonld } from '../models';
/**
 * LogLoopStepApi - axios parameter creator
 * @export
 */

export const LogLoopStepApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a LogLoopStep resource.
         * @summary Retrieves a LogLoopStep resource.
         * @param {string} id LogLoopStep identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
            logLoopStepsIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('logLoopStepsIdGet', 'id', id)
            const localVarPath = `/api/log_loop_steps/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};


/**
 * LogLoopStepApi - functional programming interface
 * @export
 */
export const LogLoopStepApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LogLoopStepApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a LogLoopStep resource.
         * @summary Retrieves a LogLoopStep resource.
         * @param {string} id LogLoopStep identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */


        async logLoopStepsIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LogLoopStepJsonld>> {
                const localVarAxiosArgs = await localVarAxiosParamCreator.logLoopStepsIdGet(id, options);

            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * Request parameters for logLoopStepsIdGet operation in LogLoopStepApi.
 * @export
 * @interface LogLoopStepApiLogLoopStepsIdGetRequest
 */
export interface LogLoopStepApiLogLoopStepsIdGetRequest {
    /**
     * LogLoopStep identifier
     * @type {string}
     * @memberof LogLoopStepApiLogLoopStepsIdGet
     */
    readonly id: string
}
/**
 * LogLoopStepApi - object-oriented interface
 * @export
 * @class LogLoopStepApi
 * @extends {BaseAPI}
 */
export class LogLoopStepApi extends BaseAPI {
    /**
     * Retrieves a LogLoopStep resource.
     * @summary Retrieves a LogLoopStep resource.
     * @param {LogLoopStepApiLogLoopStepsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogLoopStepApi
     */
    public logLoopStepsIdGet(requestParameters: LogLoopStepApiLogLoopStepsIdGetRequest, options?: AxiosRequestConfig) {

        return LogLoopStepApiFp(this.configuration).logLoopStepsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

