/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiHttpStepsGetCollection200ResponseHydraSearchHydraMappingInner } from './api-http-steps-get-collection200-response-hydra-search-hydra-mapping-inner';

/**
 * 
 * @export
 * @interface ApiHttpStepsGetCollection200ResponseHydraSearch
 */
export interface ApiHttpStepsGetCollection200ResponseHydraSearch {
    /**
     * 
     * @type {string}
     * @memberof ApiHttpStepsGetCollection200ResponseHydraSearch
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiHttpStepsGetCollection200ResponseHydraSearch
     */
    'hydra:template'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiHttpStepsGetCollection200ResponseHydraSearch
     */
    'hydra:variableRepresentation'?: string;
    /**
     * 
     * @type {Array<ApiHttpStepsGetCollection200ResponseHydraSearchHydraMappingInner>}
     * @memberof ApiHttpStepsGetCollection200ResponseHydraSearch
     */
    'hydra:mapping'?: Array<ApiHttpStepsGetCollection200ResponseHydraSearchHydraMappingInner>;
}

