/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiApiDocumentationsGetCollection200ResponseHydraSearchHydraMappingInner } from './api-api-documentations-get-collection200-response-hydra-search-hydra-mapping-inner';

/**
 * 
 * @export
 * @interface ApiApiDocumentationsGetCollection200ResponseHydraSearch
 */
export interface ApiApiDocumentationsGetCollection200ResponseHydraSearch {
    /**
     * 
     * @type {string}
     * @memberof ApiApiDocumentationsGetCollection200ResponseHydraSearch
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiApiDocumentationsGetCollection200ResponseHydraSearch
     */
    'hydra:template'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiApiDocumentationsGetCollection200ResponseHydraSearch
     */
    'hydra:variableRepresentation'?: string;
    /**
     * 
     * @type {Array<ApiApiDocumentationsGetCollection200ResponseHydraSearchHydraMappingInner>}
     * @memberof ApiApiDocumentationsGetCollection200ResponseHydraSearch
     */
    'hydra:mapping'?: Array<ApiApiDocumentationsGetCollection200ResponseHydraSearchHydraMappingInner>;
}

