/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-webhook-read-context';

/**
 * 
 * @export
 * @interface ConditionJsonld
 */
export interface ConditionJsonld {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext}
     * @memberof ConditionJsonld
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext;
    /**
     * 
     * @type {string}
     * @memberof ConditionJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConditionJsonld
     */
    'dynamicValue': string;
    /**
     * 
     * @type {any}
     * @memberof ConditionJsonld
     */
    'defaultValue'?: any;
    /**
     * 
     * @type {any}
     * @memberof ConditionJsonld
     */
    'value': any;
}

