/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-context';

/**
 * 
 * @export
 * @interface HttpResponseJsonld
 */
export interface HttpResponseJsonld {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext}
     * @memberof HttpResponseJsonld
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext;
    /**
     * 
     * @type {string}
     * @memberof HttpResponseJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpResponseJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {number}
     * @memberof HttpResponseJsonld
     */
    'statusCode'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpResponseJsonld
     */
    'headers'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpResponseJsonld
     */
    'content'?: Array<string>;
}

