/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-context';
// May contain unused imports in some cases
// @ts-ignore
import { TreatmentJsonldHttpstepReadStepRead } from './treatment-jsonld-httpstep-read-step-read';

/**
 * 
 * @export
 * @interface HttpStepJsonldHttpstepReadStepRead
 */
export interface HttpStepJsonldHttpstepReadStepRead {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'method'?: HttpStepJsonldHttpstepReadStepReadMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'content'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'headers'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'checkConditions'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<TreatmentJsonldHttpstepReadStepRead>}
     * @memberof HttpStepJsonldHttpstepReadStepRead
     */
    'treatment'?: Array<TreatmentJsonldHttpstepReadStepRead>;
}

export const HttpStepJsonldHttpstepReadStepReadMethodEnum = {
    get: 'GET',
    post: 'POST',
    delete: 'DELETE',
    patch: 'PATCH',
    put: 'PUT',
    head: 'HEAD',
    connect: 'CONNECT',
    options: 'OPTIONS',
    trace: 'TRACE'
} as const;

export type HttpStepJsonldHttpstepReadStepReadMethodEnum = typeof HttpStepJsonldHttpstepReadStepReadMethodEnum[keyof typeof HttpStepJsonldHttpstepReadStepReadMethodEnum];


