/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Treatment } from './treatment';

/**
 * 
 * @export
 * @interface HttpStep
 */
export interface HttpStep {
    /**
     * 
     * @type {string}
     * @memberof HttpStep
     */
    'scenario': string;
    /**
     * 
     * @type {string}
     * @memberof HttpStep
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpStep
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof HttpStep
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStep
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof HttpStep
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpStep
     */
    'method'?: HttpStepMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof HttpStep
     */
    'url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpStep
     */
    'content'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStep
     */
    'headers'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStep
     */
    'checkConditions'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<Treatment>}
     * @memberof HttpStep
     */
    'treatment'?: Array<Treatment>;
}

export const HttpStepMethodEnum = {
    get: 'GET',
    post: 'POST',
    delete: 'DELETE',
    patch: 'PATCH',
    put: 'PUT',
    head: 'HEAD',
    connect: 'CONNECT',
    options: 'OPTIONS',
    trace: 'TRACE'
} as const;

export type HttpStepMethodEnum = typeof HttpStepMethodEnum[keyof typeof HttpStepMethodEnum];


