/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TreatmentJsonld } from './treatment-jsonld';

/**
 * 
 * @export
 * @interface HttpStepJsonld
 */
export interface HttpStepJsonld {
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonld
     */
    'scenario': string;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonld
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonld
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof HttpStepJsonld
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonld
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof HttpStepJsonld
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonld
     */
    'method'?: HttpStepJsonldMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof HttpStepJsonld
     */
    'url'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonld
     */
    'content'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonld
     */
    'headers'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttpStepJsonld
     */
    'checkConditions'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<TreatmentJsonld>}
     * @memberof HttpStepJsonld
     */
    'treatment'?: Array<TreatmentJsonld>;
}

export const HttpStepJsonldMethodEnum = {
    get: 'GET',
    post: 'POST',
    delete: 'DELETE',
    patch: 'PATCH',
    put: 'PUT',
    head: 'HEAD',
    connect: 'CONNECT',
    options: 'OPTIONS',
    trace: 'TRACE'
} as const;

export type HttpStepJsonldMethodEnum = typeof HttpStepJsonldMethodEnum[keyof typeof HttpStepJsonldMethodEnum];


