/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepReadStep } from './log-jsonld-log-read-step-read-httpstep-read-loopstep-read-sleepstep-read-step';

/**
 * 
 * @export
 * @interface LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepRead
 */
export interface LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepRead {
    /**
     * 
     * @type {LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepReadStep}
     * @memberof LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepRead
     */
    'step'?: LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepReadStep;
}

