/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-context';
// May contain unused imports in some cases
// @ts-ignore
import { ConditionJsonld } from './condition-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { LogHttpStepJsonld } from './log-http-step-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { LogLoopStepJsonld } from './log-loop-step-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { LogSleepStepJsonld } from './log-sleep-step-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { LogSqsStepJsonld } from './log-sqs-step-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { SqsResponseJsonld } from './sqs-response-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { TreatmentJsonld } from './treatment-jsonld';

/**
 * @type LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepReadStep
 * @export
 */
export type LogJsonldLogReadStepReadHttpstepReadLoopstepReadSleepstepReadStep = LogHttpStepJsonld | LogLoopStepJsonld | LogSleepStepJsonld | LogSqsStepJsonld;


