/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-context';
// May contain unused imports in some cases
// @ts-ignore
import { ConditionJsonld } from './condition-jsonld';

/**
 * 
 * @export
 * @interface LogLoopStepJsonld
 */
export interface LogLoopStepJsonld {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext}
     * @memberof LogLoopStepJsonld
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadContext;
    /**
     * 
     * @type {string}
     * @memberof LogLoopStepJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogLoopStepJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogLoopStepJsonld
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogLoopStepJsonld
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof LogLoopStepJsonld
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogLoopStepJsonld
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof LogLoopStepJsonld
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LogLoopStepJsonld
     */
    'error'?: string | null;
    /**
     * 
     * @type {Array<ConditionJsonld>}
     * @memberof LogLoopStepJsonld
     */
    'conditions'?: Array<ConditionJsonld>;
    /**
     * 
     * @type {number}
     * @memberof LogLoopStepJsonld
     */
    'stepToReturn'?: number;
}

