/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-webhook-read-context';
// May contain unused imports in some cases
// @ts-ignore
import { HttpResponseJsonld } from './http-response-jsonld';
// May contain unused imports in some cases
// @ts-ignore
import { TreatmentJsonld } from './treatment-jsonld';

/**
 * 
 * @export
 * @interface LogHttpStepJsonld
 */
export interface LogHttpStepJsonld {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext}
     * @memberof LogHttpStepJsonld
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {HttpResponseJsonld}
     * @memberof LogHttpStepJsonld
     */
    'response'?: HttpResponseJsonld;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof LogHttpStepJsonld
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogHttpStepJsonld
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof LogHttpStepJsonld
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    'error'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    'method'?: LogHttpStepJsonldMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof LogHttpStepJsonld
     */
    'url'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogHttpStepJsonld
     */
    'content'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogHttpStepJsonld
     */
    'headers'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogHttpStepJsonld
     */
    'checkConditions'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<TreatmentJsonld>}
     * @memberof LogHttpStepJsonld
     */
    'treatment'?: Array<TreatmentJsonld>;
}

export const LogHttpStepJsonldMethodEnum = {
    get: 'GET',
    post: 'POST',
    delete: 'DELETE',
    patch: 'PATCH',
    put: 'PUT',
    head: 'HEAD',
    connect: 'CONNECT',
    options: 'OPTIONS',
    trace: 'TRACE'
} as const;

export type LogHttpStepJsonldMethodEnum = typeof LogHttpStepJsonldMethodEnum[keyof typeof LogHttpStepJsonldMethodEnum];


