/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScenarioMetrics
 */
export interface ScenarioMetrics {
    /**
     * 
     * @type {string}
     * @memberof ScenarioMetrics
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScenarioMetrics
     */
    'scenario': string;
    /**
     * 
     * @type {number}
     * @memberof ScenarioMetrics
     */
    'totalExecutions': number;
    /**
     * 
     * @type {number}
     * @memberof ScenarioMetrics
     */
    'successExecutions': number;
}

