/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScenarioJsonldScenarioWrite
 */
export interface ScenarioJsonldScenarioWrite {
    /**
     * 
     * @type {string}
     * @memberof ScenarioJsonldScenarioWrite
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ScenarioJsonldScenarioWrite
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ScenarioJsonldScenarioWrite
     */
    'cron'?: string | null;
}

