/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SqsStepJsonld
 */
export interface SqsStepJsonld {
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'scenario': string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof SqsStepJsonld
     */
    'stepNumber': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SqsStepJsonld
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof SqsStepJsonld
     */
    'runAfterFailure'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'accessKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'secretKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqsStepJsonld
     */
    'messageGroupId'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SqsStepJsonld
     */
    'content'?: { [key: string]: string; };
}

