/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Treatment
 */
export interface Treatment {
    /**
     * 
     * @type {string}
     * @memberof Treatment
     */
    'variableName': string;
    /**
     * 
     * @type {string}
     * @memberof Treatment
     */
    'contentLocation': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Treatment
     */
    'conditions': { [key: string]: string; };
}

