/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext } from './abstract-step-jsonld-scenario-read-step-read-httpstep-read-loopstep-read-sleepstep-read-sqsstep-read-metrics-read-webhook-read-context';

/**
 * 
 * @export
 * @interface WebhookJsonldWebhookRead
 */
export interface WebhookJsonldWebhookRead {
    /**
     * 
     * @type {AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext}
     * @memberof WebhookJsonldWebhookRead
     */
    '@context'?: AbstractStepJsonldScenarioReadStepReadHttpstepReadLoopstepReadSleepstepReadSqsstepReadMetricsReadWebhookReadContext;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonldWebhookRead
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonldWebhookRead
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonldWebhookRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonldWebhookRead
     */
    'eventType': WebhookJsonldWebhookReadEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonldWebhookRead
     */
    'url': string;
}

export const WebhookJsonldWebhookReadEventTypeEnum = {
    on_failure: 'onFailure',
    on_success: 'onSuccess'
} as const;

export type WebhookJsonldWebhookReadEventTypeEnum = typeof WebhookJsonldWebhookReadEventTypeEnum[keyof typeof WebhookJsonldWebhookReadEventTypeEnum];


