/* tslint:disable */
/* eslint-disable */
/**
 * Global Testing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebhookJsonld
 */
export interface WebhookJsonld {
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonld
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonld
     */
    'scenario': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonld
     */
    'eventType': WebhookJsonldEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookJsonld
     */
    'url': string;
}

export const WebhookJsonldEventTypeEnum = {
    on_failure: 'onFailure',
    on_success: 'onSuccess'
} as const;

export type WebhookJsonldEventTypeEnum = typeof WebhookJsonldEventTypeEnum[keyof typeof WebhookJsonldEventTypeEnum];


