include:
  - back/compose.yml
  - front/compose.yml

services:
  db:
    image: postgres:${POSTGRES_TAG}
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB_NAME} -U ${POSTGRES_DB_USER}"]
      start_period: 2s
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - internal
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:rw

networks:
  internal:
    name: internal

volumes:
  postgres:
