services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Mock\Sqs\AwsSqsMock:
        public: true
        class: App\Tests\Mock\Sqs\AwsSqsMock
        arguments:
          $args:
            version: 'latest'
            region: 'us-west-2'
            creadentials:
              key: 'accessKey'
              secret: 'secretKey'

    Aws\Sqs\SqsClient:
        alias: App\Tests\Mock\Sqs\AwsSqsMock
