services:
  ui:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_API_PUBLIC_URL: "http://localhost:8080"
        NEXT_PUBLIC_APP_ENV: "production"
        NEXT_PUBLIC_APP_VERSION: "1.0.0"
    image: ui
    environment:
      - "NEXT_PUBLIC_API_PUBLIC_URL=http://localhost:8080"
      - "HOSTNAME=0.0.0.0"
      - "API_INTERNAL_URL=http://api"
    ports:
      - "80:3000"
    networks:
      - proxy
      - internal

networks:
  proxy:
    name: proxy
  internal:
    name: internal
